name: CI
on:
  push:
    branches: main

  pull_request:
    branches: main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: ‘2’
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: |
            3.10
            3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade nox

    - name: Execute nox
      run: |
        nox
